### ISSUE TITLE
Issues when running "sudo dkms install -m apple-ibridge -v 0.1" on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by alexanderselergretz** [t2linux/wiki#149]
feedback:
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.14.0-1-default...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.14.0-1-default (x86_64)
Consult /var/lib/dkms/apple-ibridge/0.1/build/make.log for more information.

/var/lib/dkms/apple-ibridge/0.1/build/make.log :

DKMS make.log for apple-ibridge-0.1 for kernel 5.14.0-1-default (x86_64)
Sun Sep 12 07:51:20 PM CST 2021
make -C /lib/modules/5.14.0-1-default/build M=/var/lib/dkms/apple-ibridge/0.1/build modules
make[1]: Entering directory '/usr/src/linux-5.14.0-1-obj/x86_64/default'
  CC [M]  /var/lib/dkms/apple-ibridge/0.1/build/apple-ibridge.o
  CC [M]  /var/lib/dkms/apple-ibridge/0.1/build/apple-ib-tb.o
  CC [M]  /var/lib/dkms/apple-ibridge/0.1/build/apple-ib-als.o
/var/lib/dkms/apple-ibridge/0.1/build/apple-ib-als.c: In function ‘appleals_config_iio’:
/var/lib/dkms/apple-ibridge/0.1/build/apple-ib-als.c:490:50: error: ‘struct iio_dev’ has no member named ‘id’
  490 |                                           iio_dev->id);
      |                                                  ^~
make[3]: *** [/usr/src/linux-5.14.0-1/scripts/Makefile.build:272: /var/lib/dkms/apple-ibridge/0.1/build/apple-ib-als.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-5.14.0-1/Makefile:1865: /var/lib/dkms/apple-ibridge/0.1/build] Error 2
make[1]: *** [../../../linux-5.14.0-1/Makefile:220: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-5.14.0-1-obj/x86_64/default'
make: *** [Makefile:13: all] Error 2

**Comment by networkException** [comment]
The apple-ibridge module currently has no support for linux 5.14.x, there is an [open pull request regarding this issue[(https://github.com/t2linux/apple-ib-drv/pull/1) however, you can try compiling using this branch.

**Comment by Redecorating** [comment]
This error on old kernels has has now been fixed: https://github.com/t2linux/apple-ib-drv/commit/d8411ad1d87db8491e53887e36c3d37f445203eb

You should be able to update your copy of apple-ibridge's source by following the dkms guide again.

If you have any problems, please reopen this issue.
